name: CI/CD

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*.*'
  workflow_dispatch:
    inputs:
      environment:
        description: Development Environment
        required: true
        default: test
        type: choice
        options:
          - test
          - production

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            vastsea/vastsea-sso-frontend
          tags: |
            ${{ github.event_name == 'push' && 'type=semver,pattern={{version}}' || '' }}
            ${{ github.event_name == 'push' && 'type=raw,value=latest' || '' }}
            ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'test' && 'type=raw,value=test' || '' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_URL=${{ vars.BASE_URL }}
            AUTH_SERVER_CLIENT_ID=${{ secrets.AUTH_SERVER_CLIENT_ID }}
            VITE_AUTH_SERVER_CLIENT_ID=${{ vars.VITE_AUTH_SERVER_CLIENT_ID }}
            VITE_GT_ID=${{ vars.VITE_GT_ID }}
  deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.environment != '' }}
    steps:
      - name: SSH To Host
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            sudo bash ./deploy.sh ${{ github.event.inputs.environment || 'production' }}